<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_son123_rounded-circle shadow-1-strong me-3</name>
   <tag></tag>
   <elementGuidId>a044fa4d-d9e7-4ecd-bd48-1490ee0745e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/form/div/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle.shadow-1-strong.me-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>875a23f7-03b1-4142-9f05-029349cbac0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle shadow-1-strong me-3</value>
      <webElementGuid>3f445c82-fc66-4b81-8e94-8c2562ddb723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://scontent.fhan5-11.fna.fbcdn.net/v/t1.6435-9/67071140_115139136464060_3520023074017640448_n.jpg?_nc_cat=111&amp;ccb=1-5&amp;_nc_sid=09cbfe&amp;_nc_ohc=MhQqSe2Sp9EAX_V26Gd&amp;_nc_ht=scontent.fhan5-11.fna&amp;oh=00_AT-8tuIYZgX0dNNKQBaPzYRufRou6XFyllqdhzk7MFyonQ&amp;oe=625D2B85</value>
      <webElementGuid>abb77b8f-b6b9-4476-b6bf-35b9eb6b2979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>d3b5a4b6-e47d-432e-b1d2-e1314cd8b96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>1c2aa54f-bfcf-4044-b8c4-ce5ce025834b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>69f424a7-7368-4a33-9fc4-a078693ffc45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/form[@class=&quot;d-flex my-2 col-md-2&quot;]/div[@class=&quot;btn-group&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-success dropdown-toggle&quot;]/img[@class=&quot;rounded-circle shadow-1-strong me-3&quot;]</value>
      <webElementGuid>001ae7b6-102d-4f9c-aef7-ef788bdbf9ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/form/div/div/button/img</value>
      <webElementGuid>4ec15df3-84be-4e94-b669-652c45356053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='avatar']</value>
      <webElementGuid>5a5f73db-cac9-49e6-8d30-7e94df754064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>fba2bc76-4a9e-43ad-b5a2-c91e1fee24f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://scontent.fhan5-11.fna.fbcdn.net/v/t1.6435-9/67071140_115139136464060_3520023074017640448_n.jpg?_nc_cat=111&amp;ccb=1-5&amp;_nc_sid=09cbfe&amp;_nc_ohc=MhQqSe2Sp9EAX_V26Gd&amp;_nc_ht=scontent.fhan5-11.fna&amp;oh=00_AT-8tuIYZgX0dNNKQBaPzYRufRou6XFyllqdhzk7MFyonQ&amp;oe=625D2B85' and @alt = 'avatar']</value>
      <webElementGuid>b75be49f-f06d-46da-8284-9c435a9788cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
